### ISSUE TITLE
Convert the nextstrain csv output

### ISSUE THREAD

**Issue by culpinnis** [poysh/idee1_hypervirome_project#5]
I guess to work with the SNPs and positions in the following analysis, we should output at least:

- Position of the SNP
- Original Nucleotide
- Exchanged Nucleotide

from the converted data set of nextstrain. 
Please discuss if it is necessary and how further analysis will use this kind of data. 

See also my remarks in https://github.com/poysh/idee1_hypervirome_project/tree/dataset-prep/blast-to-snp/preprocess-data/blast-to-snp

**Comment by ghost** [comment]
@culpinnis I can help with that. In the other team to predict mutations, things are still (I guess we still need the parsed data).

**Comment by jannessm** [comment]
If I understand the problem correctly one should parse the informations of genome_annotations in the meta data of ncov.json?

**Comment by culpinnis** [comment]
Example structure: https://docs.google.com/spreadsheets/d/1x2nmyknlCAziKCiEKahYS0XdVEXY2lIKaMMv6kNdS9o/edit?usp=sharing

As far as I know, this is going to be implemented right now.

**Comment by culpinnis** [comment]
Fixed in #10
